# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import codetiming._timers as module_0

def test_case_0():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    none_type_0 = timers_0.clear()

@pytest.mark.xfail(strict=True)
def test_case_1():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    none_type_0 = None
    timers_0.min(none_type_0)

@pytest.mark.xfail(strict=True)
def test_case_2():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    timers_0.add(timers_0, timers_0)

def test_case_3():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    none_type_0 = None
    with pytest.raises(TypeError):
        timers_0.__setitem__(timers_0, none_type_0)

@pytest.mark.xfail(strict=True)
def test_case_4():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    str_0 = '0s .KMP!3NtbR'
    timers_0.total(str_0)

@pytest.mark.xfail(strict=True)
def test_case_5():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    none_type_0 = timers_0.clear()
    str_0 = '&ub^Ud'
    timers_0.mean(str_0)

@pytest.mark.xfail(strict=True)
def test_case_6():
    timers_0 = module_0.Timers()
    assert len(timers_0) == 0
    var_0 = timers_0.update(timers_0)
    timers_0.median(timers_0)