# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils_local.flutils.setuputils.cfg as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    generator_0 = module_0.each_sub_command_config()
    module_0.SetupCfgCommandConfig(*generator_0)

@pytest.mark.xfail(strict=True)
def test_case_1():
    module_0.SetupCfgCommandConfig()