# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils.setuputils.cfg as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    generator_0 = module_0.each_sub_command_config()
    module_0.SetupCfgCommandConfig(*generator_0)

def test_case_1():
    generator_0 = module_0.each_sub_command_config()

@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = '!Ji9zn~g'
    generator_0 = module_0.each_sub_command_config(str_0)
    module_0.SetupCfgCommandConfig(*generator_0)

@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = '/'
    generator_0 = module_0.each_sub_command_config(str_0)
    module_0.SetupCfgCommandConfig(*generator_0)