# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mimesis_local.mimesis.providers.transport as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    transport_0 = module_0.Transport()
    assert transport_0.seed is None
    assert f'{type(transport_0.random).__module__}.{type(transport_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = transport_0.car()
    str_1 = transport_0.airplane()
    str_2 = transport_0.car()
    none_type_0 = transport_0.reseed()
    str_3 = transport_0.truck()
    str_4 = transport_0.airplane()
    str_5 = transport_0.airplane()
    bytes_0 = b'\x90\x7f\x85\xba\xa1\x7f~\xce.\xe2\x9c;\xb5J\xfa1\x00\x1e\x06'
    str_6 = transport_0.airplane()
    transport_1 = module_0.Transport()
    transport_1.vehicle_registration_code(bytes_0)

@pytest.mark.xfail(strict=True)
def test_case_1():
    transport_0 = module_0.Transport()
    assert transport_0.seed is None
    assert f'{type(transport_0.random).__module__}.{type(transport_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = transport_0.vehicle_registration_code()
    module_0.Transport(**transport_0)

def test_case_2():
    transport_0 = module_0.Transport()
    assert transport_0.seed is None
    assert f'{type(transport_0.random).__module__}.{type(transport_0.random).__qualname__}' == 'mimesis.random.Random'

def test_case_3():
    transport_0 = module_0.Transport()
    assert transport_0.seed is None
    assert f'{type(transport_0.random).__module__}.{type(transport_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = transport_0.car()
    str_1 = transport_0.truck(str_0)

def test_case_4():
    transport_0 = module_0.Transport()
    assert transport_0.seed is None
    assert f'{type(transport_0.random).__module__}.{type(transport_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = transport_0.truck()
    str_1 = transport_0.car()
    transport_1 = module_0.Transport()
    str_2 = transport_1.airplane()
    transport_2 = module_0.Transport()
    str_3 = transport_2.truck()