# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mimesis_local.mimesis.providers.text as module_0

def test_case_0():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    none_type_0 = text_0.reseed()
    list_0 = text_0.words()
    tuple_0 = text_0.rgb_color()
    list_1 = text_0.alphabet(list_0)
    str_0 = text_0.sentence()
    text_1 = module_0.Text()
    str_1 = text_1.color()

def test_case_1():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.title()
    str_1 = text_0.color()
    assert str_1 == 'Purple'
    tuple_0 = text_0.rgb_color()
    str_2 = text_0.level()
    str_3 = text_0.swear_word()
    str_4 = text_0.text()
    list_0 = text_0.alphabet()
    str_5 = text_0.swear_word()

@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.sentence()
    list_0 = [bool_0, bool_0, bool_0]
    module_0.Text(*list_0)

def test_case_3():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.title()
    tuple_0 = text_0.rgb_color()
    str_1 = text_0.level()
    str_2 = text_0.word()
    str_3 = text_0.hex_color()

@pytest.mark.xfail(strict=True)
def test_case_4():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    none_type_0 = text_0.reseed(text_0)
    int_0 = 0
    list_0 = text_0.words(int_0)
    tuple_0 = text_0.rgb_color(text_0)
    module_0.Text(**tuple_0)

def test_case_5():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.hex_color()

def test_case_6():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.swear_word()

def test_case_7():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.quote()
    none_type_0 = None
    text_1 = module_0.Text()
    list_0 = text_1.alphabet()
    list_1 = text_1.alphabet(none_type_0)
    str_1 = text_1.answer()
    str_2 = text_1.quote()
    list_2 = text_1.alphabet()
    str_3 = text_1.word()

def test_case_8():
    text_0 = module_0.Text()
    assert f'{type(text_0).__module__}.{type(text_0).__qualname__}' == 'mimesis_local.mimesis.providers.text.Text'
    assert text_0.seed is None
    assert f'{type(text_0.random).__module__}.{type(text_0.random).__qualname__}' == 'mimesis.random.Random'
    assert text_0.locale == 'en'
    str_0 = text_0.title()
    str_1 = text_0.color()
    tuple_0 = text_0.rgb_color()
    str_2 = text_0.level()
    str_3 = text_0.word()