# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pypara_local.pypara.commons.errors as module_0

def test_case_0():
    programming_error_0 = module_0.ProgrammingError()
    assert f'{type(module_0.ProgrammingError.passert).__module__}.{type(module_0.ProgrammingError.passert).__qualname__}' == 'builtins.method'