# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.builtins.it as module_0

def test_case_0():
    italy_spec_provider_0 = module_0.ItalySpecProvider()
    assert f'{type(italy_spec_provider_0).__module__}.{type(italy_spec_provider_0).__qualname__}' == 'mimesis_local.mimesis.builtins.it.ItalySpecProvider'
    assert italy_spec_provider_0.seed is None
    assert f'{type(italy_spec_provider_0.random).__module__}.{type(italy_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert italy_spec_provider_0.locale == 'it'
    str_0 = italy_spec_provider_0.get_current_locale()
    assert str_0 == 'it'
    str_1 = italy_spec_provider_0.__str__()
    assert str_1 == 'ItalySpecProvider <it>'
    str_2 = italy_spec_provider_0.fiscal_code()

def test_case_1():
    italy_spec_provider_0 = module_0.ItalySpecProvider()
    assert f'{type(italy_spec_provider_0).__module__}.{type(italy_spec_provider_0).__qualname__}' == 'mimesis_local.mimesis.builtins.it.ItalySpecProvider'
    assert italy_spec_provider_0.seed is None
    assert f'{type(italy_spec_provider_0.random).__module__}.{type(italy_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert italy_spec_provider_0.locale == 'it'