# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils_local.flutils.validators as module_0

def test_case_0():
    str_0 = 'asdict() should be called on dataclass instances'
    with pytest.raises(SyntaxError):
        module_0.validate_identifier(str_0)

def test_case_1():
    bool_0 = True
    tuple_0 = ()
    with pytest.raises(TypeError):
        module_0.validate_identifier(bool_0, tuple_0)

def test_case_2():
    str_0 = ''
    with pytest.raises(SyntaxError):
        module_0.validate_identifier(str_0)

def test_case_3():
    str_0 = 'BCc*k'
    bool_0 = False
    with pytest.raises(SyntaxError):
        module_0.validate_identifier(str_0, bool_0)

def test_case_4():
    str_0 = '7?4:'
    with pytest.raises(SyntaxError):
        module_0.validate_identifier(str_0)

def test_case_5():
    str_0 = '__gt__'
    with pytest.raises(SyntaxError):
        module_0.validate_identifier(str_0)

def test_case_6():
    str_0 = 'c'
    none_type_0 = module_0.validate_identifier(str_0)
    none_type_1 = module_0.validate_identifier(str_0, str_0)
    with pytest.raises(TypeError):
        module_0.validate_identifier(none_type_1)