# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils.codecs.b64 as module_0
import base64 as module_1
import codecs as module_2

def test_case_0():
    str_0 = '_ath__'
    with pytest.raises(UnicodeEncodeError):
        module_0.encode(str_0, str_0)

@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = module_0.register()
    assert module_0.NAME == 'b64'
    none_type_1 = module_0.register()
    module_1.b32hexencode(none_type_0)

def test_case_2():
    bytes_0 = b'w\xb3A\xc4^*'
    int_0 = 911
    tuple_0 = (bytes_0, int_0)
    tuple_1 = module_0.encode(tuple_0)
    assert module_0.NAME == 'b64'
    str_0 = 'eutf8h'
    none_type_0 = module_0.register()
    with pytest.raises(UnicodeEncodeError):
        module_0.encode(str_0)

def test_case_3():
    str_0 = '__path__'
    tuple_0 = module_0.encode(str_0, str_0)
    assert module_0.NAME == 'b64'

@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    module_0.decode(bool_0, bool_0)

def test_case_5():
    str_0 = 'h19?'
    with pytest.raises(LookupError):
        module_2.getincrementaldecoder(str_0)