# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import pypara_local.pypara.exchange as module_0
import datetime as module_1

@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.FXRate()

@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    f_x_rate_lookup_error_0 = module_0.FXRateLookupError(none_type_0, none_type_0, none_type_0)
    assert f_x_rate_lookup_error_0.ccy1 is None
    assert f_x_rate_lookup_error_0.ccy2 is None
    assert f_x_rate_lookup_error_0.asof is None
    module_1.date()

@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b'\xbc67^\x18\tA'
    list_0 = [bytes_0, bytes_0, bytes_0, bytes_0]
    dict_0 = {}
    f_x_rate_0 = module_0.FXRate(*list_0, **dict_0)
    assert f'{type(module_0.FXRate.of).__module__}.{type(module_0.FXRate.of).__qualname__}' == 'builtins.method'
    f_x_rate_0.__invert__()