# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import pypara_local.pypara.commons.numbers as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    module_0.make_quantizer(dict_0)