# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mimesis.shortcuts as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = ')61\twp<\x0cUs'
    bool_0 = True
    var_0 = module_0.download_image(save_path=str_0, unverified_ctx=bool_0)
    str_1 = ';] '
    module_0.luhn_checksum(str_1)

@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ''
    str_1 = module_0.luhn_checksum(str_0)
    assert str_1 == '0'
    str_2 = ')61\twp<\x0cUs'
    str_3 = ';\r ~!^<~aVU\x0cO\rqv\\'
    var_0 = module_0.download_image(save_path=str_3)
    module_0.luhn_checksum(str_2)

@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b'\x90\xbe\xc5\xc4~\x8c\x82\x1c\x92\x1dD\xc6\x8b\xd2'
    str_0 = module_0.luhn_checksum(bytes_0)
    assert str_0 == '4'
    str_1 = module_0.luhn_checksum(bytes_0)
    assert str_1 == '4'
    str_2 = module_0.luhn_checksum(str_0)
    assert str_2 == '2'
    var_0 = module_0.download_image(unverified_ctx=str_0)
    str_3 = 'qyBia9dXH'
    module_0.download_image(str_3)

@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = '\x0bh\x0b?~'
    str_1 = '520'
    var_0 = module_0.download_image(save_path=str_1)
    var_1 = module_0.download_image()
    module_0.luhn_checksum(str_0)

@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = 'f{fb:gM[\r?+ne`nwBX[9'
    module_0.luhn_checksum(str_0)

@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b'\x90\xbe\xc5\xc4~\x8c\x82\x1c\x92\x1dD\xc6\x8b\xd2'
    str_0 = module_0.luhn_checksum(bytes_0)
    assert str_0 == '4'
    str_1 = 'sVLOX\x0b]._#jI3ZdBRa'
    module_0.download_image(str_1, unverified_ctx=str_1)