# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.decorators as module_0

def test_case_0():
    callable_0 = module_0.romanized()