# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mimesis.exceptions as module_0
import builtins as module_1

@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 6033.9295
    module_0.NonEnumerableError(float_0)

def test_case_1():
    unsupported_locale_0 = module_0.UnsupportedLocale()
    assert f'{type(unsupported_locale_0).__module__}.{type(unsupported_locale_0).__qualname__}' == 'mimesis.exceptions.UnsupportedLocale'
    assert unsupported_locale_0.locale is None
    assert unsupported_locale_0.message == 'Locale «{}» is not supported'
    str_0 = unsupported_locale_0.__str__()
    assert str_0 == 'Locale «None» is not supported'
    none_type_0 = None
    unsupported_locale_1 = module_0.UnsupportedLocale()
    assert unsupported_locale_1.message == 'Locale «{}» is not supported'
    non_enumerable_error_0 = module_0.NonEnumerableError(none_type_0)
    assert f'{type(non_enumerable_error_0).__module__}.{type(non_enumerable_error_0).__qualname__}' == 'mimesis.exceptions.NonEnumerableError'
    assert non_enumerable_error_0.items == ''
    assert module_0.NonEnumerableError.message == 'You should use one item of: «{}» of the object mimesis.enums.{}'
    unsupported_locale_2 = module_0.UnsupportedLocale()
    assert unsupported_locale_2.message == 'Locale «{}» is not supported'

@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    non_enumerable_error_0 = module_0.NonEnumerableError(dict_0)
    assert non_enumerable_error_0.name == {True: True}
    assert non_enumerable_error_0.items == 'True'
    assert module_0.NonEnumerableError.message == 'You should use one item of: «{}» of the object mimesis.enums.{}'
    non_enumerable_error_0.__str__()

def test_case_3():
    exception_0 = module_1.Exception()
    list_0 = [exception_0, exception_0, exception_0]
    undefined_schema_0 = module_0.UndefinedSchema(*list_0)
    str_0 = undefined_schema_0.__str__()
    assert str_0 == 'Schema should be defined in lambda.'
    unsupported_field_0 = module_0.UnsupportedField()
    assert f'{type(unsupported_field_0).__module__}.{type(unsupported_field_0).__qualname__}' == 'mimesis.exceptions.UnsupportedField'
    assert unsupported_field_0.name is None
    assert unsupported_field_0.message == 'Field «{}» is not supported.'
    str_1 = unsupported_field_0.__str__()
    assert str_1 == 'Field «None» is not supported.'

def test_case_4():
    dict_0 = {}
    undefined_field_0 = module_0.UndefinedField(**dict_0)
    str_0 = undefined_field_0.__str__()
    assert str_0 == 'Undefined field. Filed cannot be None.'
    unacceptable_field_0 = module_0.UnacceptableField()

def test_case_5():
    unacceptable_field_0 = module_0.UnacceptableField()
    str_0 = unacceptable_field_0.__str__()
    assert str_0 == 'Unacceptable field format, use **provider.method**.'
    str_1 = unacceptable_field_0.__str__()
    assert str_1 == 'Unacceptable field format, use **provider.method**.'