# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import isort.wrap_modes as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = '#E^H>x\n{Vyv[FHqW/G2'
    list_0 = [str_0]
    module_0.from_string(list_0)

@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = 'x[ACuc6O,)!j6K0Sb'
    int_0 = -2552
    module_0.vertical(str_0, str_0, str_0, str_0, int_0, int_0, str_0, str_0, int_0, int_0)

@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b'\xf5"\x9a\x8d7\x97'
    var_0 = module_0.formatter_from_string(bytes_0)
    dict_0 = {var_0: bytes_0}
    bool_0 = False
    str_0 = "'q9="
    bool_1 = False
    module_0.vertical_grid_grouped(dict_0, var_0, var_0, dict_0, bool_0, var_0, str_0, var_0, str_0, bool_1)