# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mimesis_local.mimesis.providers.code as module_0

def test_case_0():
    code_0 = module_0.Code()
    assert code_0.seed is None
    assert f'{type(code_0.random).__module__}.{type(code_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = code_0.imei()

def test_case_1():
    code_0 = module_0.Code()
    assert code_0.seed is None
    assert f'{type(code_0.random).__module__}.{type(code_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = code_0.locale_code()

def test_case_2():
    code_0 = module_0.Code()
    assert code_0.seed is None
    assert f'{type(code_0.random).__module__}.{type(code_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = code_0.ean()
    str_1 = code_0.__str__()
    none_type_0 = code_0.reseed()
    str_2 = code_0.issn()
    str_3 = code_0.isbn()
    str_4 = code_0.issn()
    str_5 = code_0.imei()

@pytest.mark.xfail(strict=True)
def test_case_3():
    code_0 = module_0.Code()
    assert code_0.seed is None
    assert f'{type(code_0.random).__module__}.{type(code_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = 'xhv\t'
    str_1 = code_0.locale_code()
    code_0.isbn(locale=str_0)

@pytest.mark.xfail(strict=True)
def test_case_4():
    list_0 = []
    code_0 = module_0.Code()
    assert code_0.seed is None
    assert f'{type(code_0.random).__module__}.{type(code_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = code_0.ean()
    bytes_0 = b'#\xd1q\xe3\xfc\x98\x85\xc3\xf8W,'
    list_1 = [list_0, list_0, list_0, bytes_0]
    module_0.Code(*list_1, **list_0)

@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    list_0 = [bool_0]
    code_0 = module_0.Code()
    assert code_0.seed is None
    assert f'{type(code_0.random).__module__}.{type(code_0.random).__qualname__}' == 'mimesis.random.Random'
    str_0 = code_0.pin()
    module_0.Code(**list_0)