# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import importlib.util as module_0
import flutils_local.flutils.moduleutils as module_1

@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "::,OMqO8'NoYdG+V>Cbl"
    module_0.source_hash(str_0)

def test_case_1():
    str_0 = 'cLw#1:y4?z'
    with pytest.raises(ImportError):
        module_1.lazy_import_module(str_0)

@pytest.mark.xfail(strict=True)
def test_case_2():
    dict_0 = {}
    module_1.cherry_pick(dict_0)

@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    cherry_pick_error_0 = module_1.CherryPickError(none_type_0, none_type_0)
    assert f'{type(cherry_pick_error_0).__module__}.{type(cherry_pick_error_0).__qualname__}' == 'flutils_local.flutils.moduleutils.CherryPickError'
    module_1._LazyLoader(none_type_0)

@pytest.mark.xfail(strict=True)
def test_case_4():
    cherry_pick_finder_0 = module_1._CherryPickFinder()
    assert f'{type(module_1._CherryPickFinder.load).__module__}.{type(module_1._CherryPickFinder.load).__qualname__}' == 'builtins.method'
    assert f'{type(module_1._CherryPickFinder.add).__module__}.{type(module_1._CherryPickFinder.add).__qualname__}' == 'builtins.method'
    var_0 = cherry_pick_finder_0.__repr__()
    assert var_0 == 'flutils_local.flutils.moduleutils._CherryPickFinder'
    none_type_0 = None
    var_1 = module_0.set_package(none_type_0)
    var_1.create_module(cherry_pick_finder_0)

@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = '%Vfvr8H2.(t.s0'
    module_1._LazyLoader(str_0)