# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils.cmdutils as module_0
import pty as module_1
import enum as module_2

def test_case_0():
    none_type_0 = None
    with pytest.raises(TypeError):
        module_0.run(none_type_0, interactive=none_type_0)

def test_case_1():
    var_0 = module_1.fork()
    with pytest.raises(TypeError):
        module_0.run(var_0, lines=var_0)

@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = 'Lut<M('
    bool_0 = True
    module_0.run(str_0, stderr=str_0, force_dimensions=str_0, interactive=bool_0)

@pytest.mark.xfail(strict=True)
def test_case_3():
    var_0 = module_1.openpty()
    module_0.run(var_0, var_0, var_0, lines=var_0, force_dimensions=var_0)

@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = 'Lut<M('
    module_0.run(str_0, stderr=str_0, force_dimensions=str_0, interactive=str_0)

@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = 'H&ZXj'
    bool_0 = True
    module_0.run(str_0, columns=bool_0, force_dimensions=bool_0, interactive=bool_0)

@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = False
    enum_dict_0 = module_2._EnumDict()
    bool_1 = True
    module_0.run(enum_dict_0, columns=bool_0, interactive=bool_1)
    bytes_0 = b'\x88\x14h\xf0;w\x06H\xe4q'
    int_0 = module_0.run(bytes_0, columns=bytes_0)