# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.builtins.da as module_0

def test_case_0():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    assert f'{type(denmark_spec_provider_0).__module__}.{type(denmark_spec_provider_0).__qualname__}' == 'mimesis_local.mimesis.builtins.da.DenmarkSpecProvider'
    assert denmark_spec_provider_0.seed is None
    assert f'{type(denmark_spec_provider_0.random).__module__}.{type(denmark_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert denmark_spec_provider_0.locale == 'da'

def test_case_1():
    denmark_spec_provider_0 = module_0.DenmarkSpecProvider()
    assert f'{type(denmark_spec_provider_0).__module__}.{type(denmark_spec_provider_0).__qualname__}' == 'mimesis_local.mimesis.builtins.da.DenmarkSpecProvider'
    assert denmark_spec_provider_0.seed is None
    assert f'{type(denmark_spec_provider_0.random).__module__}.{type(denmark_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert denmark_spec_provider_0.locale == 'da'
    str_0 = denmark_spec_provider_0.cpr()