# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sty.renderfunc as module_0

def test_case_0():
    bool_0 = True
    str_0 = module_0.eightbit_fg(bool_0)
    assert str_0 == '\x1b[38;5;Truem'
    bool_1 = False
    str_1 = module_0.rgb_fg(bool_0, bool_1, bool_0)
    assert str_1 == '\x1b[38;2;True;False;Truem'

def test_case_1():
    bool_0 = True
    str_0 = module_0.eightbit_bg(bool_0)
    assert str_0 == '\x1b[48;5;Truem'
    str_1 = module_0.sgr(bool_0)
    assert str_1 == '\x1b[Truem'
    str_2 = module_0.sgr(bool_0)
    assert str_2 == '\x1b[Truem'
    str_3 = module_0.eightbit_bg(bool_0)
    assert str_3 == '\x1b[48;5;Truem'

def test_case_2():
    int_0 = 2
    str_0 = module_0.eightbit_fg(int_0)
    assert str_0 == '\x1b[38;5;2m'
    bool_0 = False
    none_type_0 = None
    str_1 = module_0.rgb_bg(bool_0, none_type_0, none_type_0)
    assert str_1 == '\x1b[48;2;False;None;Nonem'