# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.builtins.nl as module_0

def test_case_0():
    netherlands_spec_provider_0 = module_0.NetherlandsSpecProvider()
    assert f'{type(netherlands_spec_provider_0).__module__}.{type(netherlands_spec_provider_0).__qualname__}' == 'mimesis_local.mimesis.builtins.nl.NetherlandsSpecProvider'
    assert netherlands_spec_provider_0.seed is None
    assert f'{type(netherlands_spec_provider_0.random).__module__}.{type(netherlands_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert netherlands_spec_provider_0.locale == 'nl'
    str_0 = netherlands_spec_provider_0.burgerservicenummer()
    netherlands_spec_provider_1 = module_0.NetherlandsSpecProvider()
    assert netherlands_spec_provider_1.locale == 'nl'
    str_1 = netherlands_spec_provider_1.get_current_locale()
    assert str_1 == 'nl'
    str_2 = netherlands_spec_provider_0.burgerservicenummer()
    str_3 = netherlands_spec_provider_1.burgerservicenummer()

def test_case_1():
    netherlands_spec_provider_0 = module_0.NetherlandsSpecProvider()
    assert f'{type(netherlands_spec_provider_0).__module__}.{type(netherlands_spec_provider_0).__qualname__}' == 'mimesis_local.mimesis.builtins.nl.NetherlandsSpecProvider'
    assert netherlands_spec_provider_0.seed is None
    assert f'{type(netherlands_spec_provider_0.random).__module__}.{type(netherlands_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert netherlands_spec_provider_0.locale == 'nl'
    str_0 = netherlands_spec_provider_0.burgerservicenummer()
    netherlands_spec_provider_1 = module_0.NetherlandsSpecProvider()
    assert netherlands_spec_provider_1.locale == 'nl'