# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils.moduleutils as module_0
import importlib.util as module_1

@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0._LazyModule()

def test_case_1():
    str_0 = '4Hai/j"\nQ\x0bNu[U}>'
    with pytest.raises(ImportError):
        module_0.lazy_import_module(str_0, str_0)

@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = '%Vfvs8H2.)t.s0'
    module_0._LazyLoader(str_0)

def test_case_3():
    str_0 = '4Hai/j"\nQ\x0bNu[U}>'
    with pytest.raises(ImportError):
        module_0.lazy_import_module(str_0)

def test_case_4():
    str_0 = '\nli'
    var_0 = module_1.find_spec(str_0)
    cherry_pick_error_0 = module_0.CherryPickError(str_0, str_0)
    assert f'{type(cherry_pick_error_0).__module__}.{type(cherry_pick_error_0).__qualname__}' == 'flutils.moduleutils.CherryPickError'

@pytest.mark.xfail(strict=True)
def test_case_5():
    cherry_picking_loader_0 = module_0._CherryPickingLoader()
    cherry_picking_loader_0.create_module(cherry_picking_loader_0)

def test_case_6():
    cherry_pick_finder_0 = module_0._CherryPickFinder()
    assert f'{type(module_0._CherryPickFinder.load).__module__}.{type(module_0._CherryPickFinder.load).__qualname__}' == 'builtins.method'
    assert f'{type(module_0._CherryPickFinder.add).__module__}.{type(module_0._CherryPickFinder.add).__qualname__}' == 'builtins.method'

@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = '\nlis'
    cherry_picking_loader_0 = module_0._CherryPickingLoader()
    lazy_loader_0 = module_0._LazyLoader(cherry_picking_loader_0)
    assert f'{type(lazy_loader_0).__module__}.{type(lazy_loader_0).__qualname__}' == 'flutils.moduleutils._LazyLoader'
    assert f'{type(lazy_loader_0.loader).__module__}.{type(lazy_loader_0.loader).__qualname__}' == 'flutils.moduleutils._CherryPickingLoader'
    cherry_pick_error_0 = module_0.CherryPickError(str_0, str_0)
    assert f'{type(cherry_pick_error_0).__module__}.{type(cherry_pick_error_0).__qualname__}' == 'flutils.moduleutils.CherryPickError'
    var_0 = module_1.set_package(str_0)
    var_1 = module_1.find_spec(str_0)
    cherry_pick_error_1 = module_0.CherryPickError(str_0, str_0)
    dict_0 = {}
    module_0.cherry_pick(dict_0)

def test_case_8():
    str_0 = 'du'
    cherry_picking_module_0 = module_0._CherryPickingModule(*str_0)
    with pytest.raises(ImportError):
        module_0.lazy_import_module(str_0, cherry_picking_module_0)

@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = '\nli'
    cherry_pick_finder_0 = module_0._CherryPickFinder()
    assert f'{type(module_0._CherryPickFinder.load).__module__}.{type(module_0._CherryPickFinder.load).__qualname__}' == 'builtins.method'
    assert f'{type(module_0._CherryPickFinder.add).__module__}.{type(module_0._CherryPickFinder.add).__qualname__}' == 'builtins.method'
    var_0 = cherry_pick_finder_0.__repr__()
    assert var_0 == 'flutils.moduleutils._CherryPickFinder'
    var_1 = module_1.find_spec(str_0)
    cherry_pick_error_0 = module_0.CherryPickError(str_0, str_0)
    assert f'{type(cherry_pick_error_0).__module__}.{type(cherry_pick_error_0).__qualname__}' == 'flutils.moduleutils.CherryPickError'
    dict_0 = {}
    module_0.cherry_pick(dict_0)

def test_case_10():
    str_0 = ''
    with pytest.raises(ImportError):
        module_0.lazy_import_module(str_0, str_0)

@pytest.mark.xfail(strict=True)
def test_case_11():
    dict_0 = {}
    module_0.cherry_pick(dict_0)

@pytest.mark.xfail(strict=True)
def test_case_12():
    cherry_picking_loader_0 = module_0._CherryPickingLoader()
    none_type_0 = None
    var_0 = module_1.set_loader(none_type_0)
    lazy_loader_0 = module_0._LazyLoader(cherry_picking_loader_0)
    assert f'{type(lazy_loader_0).__module__}.{type(lazy_loader_0).__qualname__}' == 'flutils.moduleutils._LazyLoader'
    assert f'{type(lazy_loader_0.loader).__module__}.{type(lazy_loader_0.loader).__qualname__}' == 'flutils.moduleutils._CherryPickingLoader'
    lazy_loader_0.exec_module(var_0)

@pytest.mark.xfail(strict=True)
def test_case_13():
    cherry_picking_loader_0 = module_0._CherryPickingLoader()
    lazy_loader_0 = module_0._LazyLoader(cherry_picking_loader_0)
    assert f'{type(lazy_loader_0).__module__}.{type(lazy_loader_0).__qualname__}' == 'flutils.moduleutils._LazyLoader'
    assert f'{type(lazy_loader_0.loader).__module__}.{type(lazy_loader_0.loader).__qualname__}' == 'flutils.moduleutils._CherryPickingLoader'
    none_type_0 = None
    lazy_loader_0.load_module(none_type_0)

@pytest.mark.xfail(strict=True)
def test_case_14():
    str_0 = '56UhbZ'
    list_0 = [str_0]
    cherry_pick_error_0 = module_0.CherryPickError(str_0, list_0)
    assert f'{type(cherry_pick_error_0).__module__}.{type(cherry_pick_error_0).__qualname__}' == 'flutils.moduleutils.CherryPickError'
    lazy_module_0 = module_0._LazyModule(*list_0)
    module_0.lazy_import_module(lazy_module_0, list_0)

@pytest.mark.xfail(strict=True)
def test_case_15():
    str_0 = 'socket'
    module_0 = module_0.lazy_import_module(str_0)
    module_0._LazyModule()