# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import tests.test_codetiming as module_0

def test_case_0():
    var_0 = module_0.waste_time()
    assert module_0.TIME_PREFIX == 'Wasted time:'
    assert module_0.TIME_MESSAGE == 'Wasted time: {:.4f} seconds'

def test_case_1():
    var_0 = module_0.decorated_timewaste()
    assert module_0.TIME_PREFIX == 'Wasted time:'
    assert module_0.TIME_MESSAGE == 'Wasted time: {:.4f} seconds'

def test_case_2():
    var_0 = module_0.accumulated_timewaste()
    assert module_0.TIME_PREFIX == 'Wasted time:'
    assert module_0.TIME_MESSAGE == 'Wasted time: {:.4f} seconds'

def test_case_3():
    custom_logger_0 = module_0.CustomLogger()
    assert custom_logger_0.messages == ''
    assert module_0.TIME_PREFIX == 'Wasted time:'
    assert module_0.TIME_MESSAGE == 'Wasted time: {:.4f} seconds'

@pytest.mark.xfail(strict=True)
def test_case_4():
    custom_logger_0 = module_0.CustomLogger()
    assert custom_logger_0.messages == ''
    assert module_0.TIME_PREFIX == 'Wasted time:'
    assert module_0.TIME_MESSAGE == 'Wasted time: {:.4f} seconds'
    custom_logger_0.__call__(custom_logger_0)