# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils_local.flutils.cmdutils as module_0
import pty as module_1

def test_case_0():
    float_0 = -468.0
    int_0 = -1052
    with pytest.raises(TypeError):
        module_0.run(float_0, columns=int_0)

@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ''
    bool_0 = True
    module_0.run(str_0, lines=str_0, force_dimensions=bool_0, interactive=str_0)

def test_case_2():
    var_0 = module_1.openpty()
    with pytest.raises(TypeError):
        module_0.run(var_0, var_0, columns=var_0, lines=var_0, interactive=var_0)

@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = ''
    bool_0 = False
    module_0.run(str_0, lines=str_0, force_dimensions=bool_0, interactive=str_0)

def test_case_4():
    var_0 = module_1.openpty()
    with pytest.raises(TypeError):
        module_0.run(var_0, stderr=var_0, lines=var_0)