# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.providers.clothing as module_0

def test_case_0():
    clothing_0 = module_0.Clothing()
    bytes_0 = b'@\x15_\xaa\xe7\xa6*\re\xa0N'
    clothing_1 = module_0.Clothing(bytes_0)
    int_0 = clothing_1.custom_size()
    assert int_0 == 48

def test_case_1():
    int_0 = 879
    clothing_0 = module_0.Clothing(int_0)
    str_0 = clothing_0.__str__()
    str_1 = clothing_0.international_size()
    assert str_1 == 'M'

def test_case_2():
    clothing_0 = module_0.Clothing()
    int_0 = clothing_0.european_size()
    str_0 = clothing_0.__str__()
    none_type_0 = clothing_0.reseed()