# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.builtins.base as module_0

def test_case_0():
    base_spec_provider_0 = module_0.BaseSpecProvider()
    assert base_spec_provider_0.seed is None
    assert f'{type(base_spec_provider_0.random).__module__}.{type(base_spec_provider_0.random).__qualname__}' == 'mimesis.random.Random'
    assert base_spec_provider_0.locale == 'en'