# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import flutils_local.flutils.decorators as module_0

def test_case_0():
    bytes_0 = b':\xc7\x1cS:\x19<\xbci\xde'
    cached_property_0 = module_0.cached_property(bytes_0)
    assert f'{type(cached_property_0).__module__}.{type(cached_property_0).__qualname__}' == 'flutils_local.flutils.decorators.cached_property'
    assert cached_property_0.func == b':\xc7\x1cS:\x19<\xbci\xde'
    none_type_0 = None
    cached_property_1 = module_0.cached_property(bytes_0)
    cached_property_2 = module_0.cached_property(none_type_0)
    none_type_1 = None
    none_type_2 = None
    cached_property_3 = module_0.cached_property(none_type_2)
    var_0 = cached_property_3.__get__(none_type_1, none_type_1)
    assert f'{type(var_0).__module__}.{type(var_0).__qualname__}' == 'flutils_local.flutils.decorators.cached_property'
    assert var_0.func is None

@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b'\x8e\xf0]\xc1$2\x9a\x82f\x80'
    none_type_0 = None
    int_0 = -1793
    cached_property_0 = module_0.cached_property(int_0)
    assert f'{type(cached_property_0).__module__}.{type(cached_property_0).__qualname__}' == 'flutils_local.flutils.decorators.cached_property'
    assert cached_property_0.func == -1793
    cached_property_0.__get__(bytes_0, none_type_0)

def test_case_2():
    none_type_0 = None
    cached_property_0 = module_0.cached_property(none_type_0)
    assert f'{type(cached_property_0).__module__}.{type(cached_property_0).__qualname__}' == 'flutils_local.flutils.decorators.cached_property'
    assert cached_property_0.func is None