# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mimesis_local.mimesis.providers.path as module_0

def test_case_0():
    path_0 = module_0.Path()
    assert f'{type(path_0).__module__}.{type(path_0).__qualname__}' == 'mimesis_local.mimesis.providers.path.Path'
    assert path_0.seed is None
    assert f'{type(path_0.random).__module__}.{type(path_0.random).__qualname__}' == 'mimesis.random.Random'
    assert path_0.platform == 'linux'

def test_case_1():
    path_0 = module_0.Path()
    assert f'{type(path_0).__module__}.{type(path_0).__qualname__}' == 'mimesis_local.mimesis.providers.path.Path'
    assert path_0.seed is None
    assert f'{type(path_0.random).__module__}.{type(path_0.random).__qualname__}' == 'mimesis.random.Random'
    assert path_0.platform == 'linux'
    str_0 = path_0.project_dir()
    str_1 = path_0.users_folder()

def test_case_2():
    dict_0 = {}
    path_0 = module_0.Path(**dict_0)
    assert f'{type(path_0).__module__}.{type(path_0).__qualname__}' == 'mimesis_local.mimesis.providers.path.Path'
    assert path_0.seed is None
    assert f'{type(path_0.random).__module__}.{type(path_0.random).__qualname__}' == 'mimesis.random.Random'
    assert path_0.platform == 'linux'
    str_0 = path_0.dev_dir()
    path_1 = module_0.Path()
    str_1 = path_1.users_folder()
    str_2 = path_1.root()
    assert str_2 == '/'
    str_3 = path_1.root()
    assert str_3 == '/'

def test_case_3():
    path_0 = module_0.Path()
    assert f'{type(path_0).__module__}.{type(path_0).__qualname__}' == 'mimesis_local.mimesis.providers.path.Path'
    assert path_0.seed is None
    assert f'{type(path_0.random).__module__}.{type(path_0.random).__qualname__}' == 'mimesis.random.Random'
    assert path_0.platform == 'linux'
    path_1 = module_0.Path()
    assert path_1.seed is None
    assert f'{type(path_1.random).__module__}.{type(path_1.random).__qualname__}' == 'mimesis.random.Random'
    assert path_1.platform == 'linux'
    str_0 = path_1.project_dir()
    str_1 = path_1.home()
    assert str_1 == '/home'
    str_2 = path_0.root()
    assert str_2 == '/'
    str_3 = path_1.root()
    assert str_3 == '/'
    str_4 = path_0.project_dir()
    str_5 = path_0.home()
    assert str_5 == '/home'
    str_6 = path_1.root()
    assert str_6 == '/'
    str_7 = path_0.project_dir()
    str_8 = path_1.users_folder()